# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4

notifications:
  email: false

sudo: false

services:
  - mysql
  - postgresql
  - redis

language: python

dist: precise

cache:
  - pip

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" DEPLOY=true
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.5"

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "Fbqa+pT8riuZhDCOzZ79SBz/YFFIcFUmgAdfbZLfIxbYnf59UuF+21dMMsUlbwUiUbY2qm9EgQQDwVGRGVyFNuEebCvXjbhUH0fN41AQR+k/Voh9dp9QDh4qkmq9P3V7yI3rnerEJnxq91xRisZAXvfTyaLF0bn3AHoDp91SpjdTD1jO1WDZuVr8zOUH5l2PNY2uVbVwwHzi0hh1OEvkUxhR61nhgrn61qDNzzaGPkE3tz9O3v/hfOoKxGaT8HUUOkLEYMa9iHTL3LnmKfz5fUSJ/wMIEhHmLQasyolDwOnseL9Jb8ST0mVVA5JPzEfL/D/kaDKmuAhsvtbKKTBNC6LKoi0Acv1xviC7gGVl9HGqUtqrKurcUe0mgPfNLJdRDO6v+tofC1ielEazRwfs7qJOf4IVYY+LgU7GcT+2LZcW0ClwklSFmYyjH1NUIeoYNbw/FGZ/UjKItY59wdr9PJ3q18+GY0GlyNASI9tEXS3jQFfJkr65Xp6YBnVFpLRsq2RtxnRJP37hksm4QbFviLvHBp4DtQ0Pf56f2ubD8Z3nIfdejmU4ipy3i6nNXsIZ3ivTo1RvAWkhIxPQorAcY6aweurKXjDJBGJLSr8GIPykDLi/zCkFjMIIWyL4gg7kYAGfBtu0d3dbbbK+Vb/HKNC84uj5yV2KLRSkVSgFW2E="
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $DEPLOY = true
